//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EW2 {
    
    
    public sealed class ScreenIds {
        
        public const string campaign_info = "Art/Prefabs/Screens/campaign_info";
        
        public const string comunity_popup = "Art/Prefabs/Screens/comunity_popup";
        
        public const string daily_reward = "Art/Prefabs/Screens/daily_reward";
        
        public const string defensive_buff_panel = "Art/Prefabs/Screens/defensive_buff_panel";
        
        public const string first_purchase_popup = "Art/Prefabs/Screens/first_purchase_popup";
        
        public const string gacha_scene = "Art/Prefabs/Screens/gacha_scene";
        
        public const string game_defeat = "Art/Prefabs/Screens/game_defeat";
        
        public const string game_pause = "Art/Prefabs/Screens/game_pause";
        
        public const string game_play = "Art/Prefabs/Screens/game_play";
        
        public const string game_play_hero_defense = "Art/Prefabs/Screens/game_play_hero_defense";
        
        public const string game_play_tournament = "Art/Prefabs/Screens/game_play_tournament";
        
        public const string game_victory = "Art/Prefabs/Screens/game_victory";
        
        public const string glory_road_getmore = "Art/Prefabs/Screens/glory_road_getmore";
        
        public const string hero_4_bundle = "Art/Prefabs/Screens/hero_4_bundle";
        
        public const string hero_4_resource_flash_sale = "Art/Prefabs/Screens/hero_4_resource_flash_sale";
        
        public const string hero_academy_event = "Art/Prefabs/Screens/hero_academy_event";
        
        public const string hero_defend_mode_scene = "Art/Prefabs/Screens/hero_defend_mode_scene";
        
        public const string hero_defend_select_hero = "Art/Prefabs/Screens/hero_defend_select_hero";
        
        public const string hero_defense_result = "Art/Prefabs/Screens/hero_defense_result";
        
        public const string hero_room_scene = "Art/Prefabs/Screens/hero_room_scene";
        
        public const string home = "Art/Prefabs/Screens/home";
        
        public const string item_info = "Art/Prefabs/Screens/item_info";
        
        public const string loading = "Art/Prefabs/Screens/loading";
        
        public const string multi_reward = "Art/Prefabs/Screens/multi_reward";
        
        public const string new_enemies_popup = "Art/Prefabs/Screens/new_enemies_popup";
        
        public const string new_hero_event = "Art/Prefabs/Screens/new_hero_event";
        
        public const string patch_note = "Art/Prefabs/Screens/patch_note";
        
        public const string popp_starter_pack = "Art/Prefabs/Screens/popp_starter_pack";
        
        public const string popup_buff_dsp = "Art/Prefabs/Screens/popup_buff_dsp";
        
        public const string popup_buy_confirm = "Art/Prefabs/Screens/popup_buy_confirm";
        
        public const string popup_buy_now = "Art/Prefabs/Screens/popup_buy_now";
        
        public const string popup_buy_stamina = "Art/Prefabs/Screens/popup_buy_stamina";
        
        public const string popup_buy_tournament_ticket = "Art/Prefabs/Screens/popup_buy_tournament_ticket";
        
        public const string popup_change_avatar = "Art/Prefabs/Screens/popup_change_avatar";
        
        public const string popup_change_buff = "Art/Prefabs/Screens/popup_change_buff";
        
        public const string popup_change_name = "Art/Prefabs/Screens/popup_change_name";
        
        public const string popup_cheat = "Art/Prefabs/Screens/popup_cheat";
        
        public const string popup_claim_reward_tournament = "Art/Prefabs/Screens/popup_claim_reward_tournament";
        
        public const string popup_enhance_rune = "Art/Prefabs/Screens/popup_enhance_rune";
        
        public const string popup_giftcode = "Art/Prefabs/Screens/popup_giftcode";
        
        public const string popup_info = "Art/Prefabs/Screens/popup_info";
        
        public const string popup_info_big = "Art/Prefabs/Screens/popup_info_big";
        
        public const string popup_leaderboard_top_player = "Art/Prefabs/Screens/popup_leaderboard_top_player";
        
        public const string popup_notice = "Art/Prefabs/Screens/popup_notice";
        
        public const string popup_notice_dismantle = "Art/Prefabs/Screens/popup_notice_dismantle";
        
        public const string popup_notice_dont_ask_again_today = "Art/Prefabs/Screens/popup_notice_dont_ask_again_today";
        
        public const string popup_notice_introduce_neetan = "Art/Prefabs/Screens/popup_notice_introduce_neetan";
        
        public const string popup_notice_text = "Art/Prefabs/Screens/popup_notice_text";
        
        public const string popup_notice_unlock_system = "Art/Prefabs/Screens/popup_notice_unlock_system";
        
        public const string popup_out_of_tournament_ticket = "Art/Prefabs/Screens/popup_out_of_tournament_ticket";
        
        public const string popup_pick_language = "Art/Prefabs/Screens/popup_pick_language";
        
        public const string popup_preview_reward_defense_mode = "Art/Prefabs/Screens/popup_preview_reward_defense_mode";
        
        public const string popup_profile = "Art/Prefabs/Screens/popup_profile";
        
        public const string popup_quit_game = "Art/Prefabs/Screens/popup_quit_game";
        
        public const string popup_rating = "Art/Prefabs/Screens/popup_rating";
        
        public const string popup_reward_tournament = "Art/Prefabs/Screens/popup_reward_tournament";
        
        public const string popup_select_defend_point = "Art/Prefabs/Screens/popup_select_defend_point";
        
        public const string popup_setting = "Art/Prefabs/Screens/popup_setting";
        
        public const string popup_shard_conversion = "Art/Prefabs/Screens/popup_shard_conversion";
        
        public const string popup_spell_info = "Art/Prefabs/Screens/popup_spell_info";
        
        public const string popup_spell_package = "Art/Prefabs/Screens/popup_spell_package";
        
        public const string popup_tournament_spell_banned = "Art/Prefabs/Screens/popup_tournament_spell_banned";
        
        public const string popup_unlock_defend_point = "Art/Prefabs/Screens/popup_unlock_defend_point";
        
        public const string pre_register = "Art/Prefabs/Screens/pre_register";
        
        public const string quest_scene = "Art/Prefabs/Screens/quest_scene";
        
        public const string rewarded_ads = "Art/Prefabs/Screens/rewarded_ads";
        
        public const string rune_flash_sale = "Art/Prefabs/Screens/rune_flash_sale";
        
        public const string rune_gacha_info = "Art/Prefabs/Screens/rune_gacha_info";
        
        public const string rune_inventory_info = "Art/Prefabs/Screens/rune_inventory_info";
        
        public const string rune_package = "Art/Prefabs/Screens/rune_package";
        
        public const string shop_scene = "Art/Prefabs/Screens/shop_scene";
        
        public const string single_reward = "Art/Prefabs/Screens/single_reward";
        
        public const string spell_flash_sale = "Art/Prefabs/Screens/spell_flash_sale";
        
        public const string spell_gacha_info = "Art/Prefabs/Screens/spell_gacha_info";
        
        public const string tap_to_start = "Art/Prefabs/Screens/tap_to_start";
        
        public const string toast_short_noti_panel = "Art/Prefabs/Screens/toast_short_noti_panel";
        
        public const string tournament_lobby = "Art/Prefabs/Screens/tournament_lobby";
        
        public const string tournament_result = "Art/Prefabs/Screens/tournament_result";
        
        public const string tournament_select_heroes_popup = "Art/Prefabs/Screens/tournament_select_heroes_popup";
        
        public const string tower_upgrade_system = "Art/Prefabs/Screens/tower_upgrade_system";
        
        public const string tutorial = "Art/Prefabs/Screens/tutorial";
    }
}
