// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_monster_hunter_iv = "CgkIiPSmhL8GEAIQGQ"; // <GPGSID>
        public const string achievement_the_great_tactician_iii = "CgkIiPSmhL8GEAIQEg"; // <GPGSID>
        public const string achievement_monster_hunter_ii = "CgkIiPSmhL8GEAIQDQ"; // <GPGSID>
        public const string achievement_frozen_land_iv = "CgkIiPSmhL8GEAIQGw"; // <GPGSID>
        public const string achievement_i_need_more_power_iv = "CgkIiPSmhL8GEAIQCw"; // <GPGSID>
        public const string achievement_i_need_more_gems_ii = "CgkIiPSmhL8GEAIQEQ"; // <GPGSID>
        public const string achievement_monster_hunter_iii = "CgkIiPSmhL8GEAIQEw"; // <GPGSID>
        public const string leaderboard_leaderboard = "CgkIiPSmhL8GEAIQAQ"; // <GPGSID>
        public const string achievement_i_need_more_power_ii = "CgkIiPSmhL8GEAIQCQ"; // <GPGSID>
        public const string achievement_star_collector_i = "CgkIiPSmhL8GEAIQBg"; // <GPGSID>
        public const string achievement_i_need_more_gems_iv = "CgkIiPSmhL8GEAIQHQ"; // <GPGSID>
        public const string achievement_armageddon_iii = "CgkIiPSmhL8GEAIQFA"; // <GPGSID>
        public const string achievement_the_great_tactician_i = "CgkIiPSmhL8GEAIQAg"; // <GPGSID>
        public const string achievement_i_need_more_gem = "CgkIiPSmhL8GEAIQBw"; // <GPGSID>
        public const string achievement_monster_hunter_i = "CgkIiPSmhL8GEAIQAw"; // <GPGSID>
        public const string achievement_the_great_tactician_ii = "CgkIiPSmhL8GEAIQDA"; // <GPGSID>
        public const string achievement_star_collector_iii = "CgkIiPSmhL8GEAIQFg"; // <GPGSID>
        public const string achievement_i_need_more_gems_iii = "CgkIiPSmhL8GEAIQFw"; // <GPGSID>
        public const string achievement_star_collector_iv = "CgkIiPSmhL8GEAIQHA"; // <GPGSID>
        public const string achievement_i_need_more_power = "CgkIiPSmhL8GEAIQCA"; // <GPGSID>
        public const string achievement_i_need_more_power_iii = "CgkIiPSmhL8GEAIQCg"; // <GPGSID>
        public const string achievement_armageddon_iv = "CgkIiPSmhL8GEAIQGg"; // <GPGSID>
        public const string achievement_frozen_land_ii = "CgkIiPSmhL8GEAIQDw"; // <GPGSID>
        public const string achievement_armageddon_ii = "CgkIiPSmhL8GEAIQDg"; // <GPGSID>
        public const string achievement_frozen_land_i = "CgkIiPSmhL8GEAIQBQ"; // <GPGSID>
        public const string achievement_armageddon_i = "CgkIiPSmhL8GEAIQBA"; // <GPGSID>
        public const string achievement_star_collector_ii = "CgkIiPSmhL8GEAIQEA"; // <GPGSID>
        public const string achievement_the_great_tactician_iv = "CgkIiPSmhL8GEAIQGA"; // <GPGSID>
        public const string achievement_frozen_land_iii = "CgkIiPSmhL8GEAIQFQ"; // <GPGSID>

}

