//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zitga.UIFramework.Examples {
    
    
    public sealed class ScreenIds {
        
        public const string CameraProjectionWindow = "Prefabs/Screens/CameraProjectionWindow";
        
        public const string ConfirmationPopup = "Prefabs/Screens/ConfirmationPopup";
        
        public const string HomeWindow = "Prefabs/Screens/HomeWindow";
        
        public const string NavigationPanel = "Prefabs/Screens/NavigationPanel";
        
        public const string PlayerWindow = "Prefabs/Screens/PlayerWindow";
        
        public const string PopupExampleWindow = "Prefabs/Screens/PopupExampleWindow";
        
        public const string StartGameWindow = "Prefabs/Screens/StartGameWindow";
        
        public const string ThreeDExample = "Prefabs/Screens/ThreeDExample";
        
        public const string ToastPanel = "Prefabs/Screens/ToastPanel";
    }
}
